### ISSUE TITLE
ScriptsFilterProxy::setSearchText calls nonexistent QSortFilterProxyModel::endFilterChange()

### ISSUE THREAD

**Issue by CodeXTF2** [Adaptix-Framework/AdaptixC2#352]
`ScriptsFilterProxy::setSearchText()` in `AdaptixClient/Headers/UI/Widgets/ScriptsWidget.h:62`
calls `beginFilterChange()` then `endFilterChange()`. `endFilterChange()` doesn't exist in Qt.
Checked the Qt 6.9.2 headers (`qsortfilterproxymodel.h`): only `beginFilterChange()`,
`invalidateFilter()`, `invalidateRowsFilter()`, `invalidateColumnsFilter()` are declared.

Breaks any clean build of `testing-v2.0`. Introduced in d1f840e ("2.0 init").

Every other filter proxy in the codebase uses `invalidateFilter()` for this. Fix uses the
same pattern instead of the broken begin/end pairing.

Build:
```
cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/qt/6.9.2/gcc_64 && cmake --build build -j$(nproc)
```
Qt 6.9.2, gcc (Ubuntu 22.04)

```
In file included from /src/build/AdaptixClient_autogen/R3KP42AP2X/moc_ScriptsWidget.cpp:9,
                 from /src/build/AdaptixClient_autogen/mocs_compilation.cpp:43:
.../Headers/UI/Widgets/ScriptsWidget.h: In member function 'void ScriptsFilterProxy::setSearchText(const QString&)':
.../Headers/UI/Widgets/ScriptsWidget.h:62:89: error: 'endFilterChange' was not declared in this scope; did you mean 'beginFilterChange'?
   62 |     void setSearchText(const QString& text) { m_searchText = text; beginFilterChange(); endFilterChange(); }
      |                                                                                         ^~~~~~~~~~~~~~~
      |                                                                                         beginFilterChange
gmake[2]: *** [CMakeFiles/AdaptixClient.dir/build.make:291: CMakeFiles/AdaptixClient.dir/AdaptixClient_autogen/mocs_compilation.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:160: CMakeFiles/AdaptixClient.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by RalfHacker** [comment]
fixed
